# Site settings
title: Jianwei Blog
SEOTitle: 健伟的博客 | Jw Blog
header-img: img/post-bg-desk.jpg
email: zjianweixs@gmail.com
description: "你的问题主要在于，读书不多而想太多"
keyword: "Web, 运维, Docker, Kubernetes, 自动化, Jw, JW Blog, 健伟的博客, jianweixs"
url: "http://jianweixs.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/jianweixs/jianweixs.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-by-jianwei.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     jianweixs
zhihu_username:     si-nian-cheng-hui-jin
github_username:    jianweixs
#facebook_username:  zjianweixs
jianshu_username:   82e47294c479
#twitter_username:   none




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: jianweixs

# Gitalk
#gitalk:
#  enable: true    #是否开启Gitalk评论
#  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
#  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
#  repo: jianweixs.github.io    #仓库名称
#  owner: jianweixs    #github用户名
#  admin: jianweixs
#  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-136795556-1'            # Format: UA-xxxxxx-xx
ga_domain: jianweixs.github.io               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "简书·shakura",
        href: "https://www.jianshu.com/u/82e47294c479"
    }
]
